// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
use std::{env, fs, path::Path};

const NOVAROCKS_IDL_DIR: &str = "../../idl/novarocks";

fn idl_path(file: &str) -> std::path::PathBuf {
    Path::new(NOVAROCKS_IDL_DIR).join(file)
}

fn emit_proto_root_mod(out_dir: &Path) {
    fs::write(
        out_dir.join("proto_root_mod.rs"),
        r#"// @generated by build.rs
pub mod proto {
    pub use novarocks_protocol::{common, expr, filter, plan};

    pub mod novarocks {
        pub use novarocks_protocol::novarocks::*;
        tonic::include_proto!("novarocks");
    }
}
"#,
    )
    .expect("write proto_root_mod.rs");
}

fn main() {
    for file in [
        "common.proto",
        "expr.proto",
        "filter.proto",
        "plan.proto",
        "service.proto",
    ] {
        println!("cargo:rerun-if-changed={}", idl_path(file).display());
    }

    let out_dir = std::path::PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let protoc = protoc_bin_vendored::protoc_bin_path().expect("vendored protoc path");
    unsafe { env::set_var("PROTOC", protoc) };

    // Native DTOs and their descriptor set are owned by novarocks-protocol.
    // Core generates only Tonic service stubs against those external DTO paths.
    let protos = [
        idl_path("common.proto"),
        idl_path("expr.proto"),
        idl_path("filter.proto"),
        idl_path("plan.proto"),
        idl_path("service.proto"),
    ];
    tonic_build::configure()
        .build_client(true)
        .build_server(true)
        .codec_path("crate::protocol::native::codec::NativeProstCodec")
        .extern_path(".novarocks.common", "::novarocks_protocol::common")
        .extern_path(".novarocks.expr", "::novarocks_protocol::expr")
        .extern_path(".novarocks.filter", "::novarocks_protocol::filter")
        .extern_path(".novarocks.plan", "::novarocks_protocol::plan")
        .extern_path(".novarocks", "::novarocks_protocol::novarocks")
        .compile_protos(&protos, &[NOVAROCKS_IDL_DIR])
        .expect("compile novarocks Tonic service stubs against protocol DTOs");

    emit_proto_root_mod(&out_dir);
}
