// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to you under the Apache License, Version 2.0.

//! Generates and validates the repository-wide SQL error descriptor manifest.
//!
//! This independent package is the only aggregate owner. Domain crates export
//! descriptors; the tool never discovers them by scanning Rust source.

use std::collections::{BTreeMap, HashSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use novarocks_parser::ERROR_CODE_DESCRIPTORS;
use novarocks_user_error::{ErrorCodeDescriptor, ErrorCodeStatus, ErrorPhase};

const SCHEMA_VERSION: u32 = 1;
const MANIFEST_NAME: &str = "error-manifest-v1.tsv";
const LEDGER_NAME: &str = "error-ledger-v1.tsv";
const HEADER: &str = "# generated by novarocks-error-manifest; do not edit.\n";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct LedgerEntry {
    phase: ErrorPhase,
    status: ErrorCodeStatus,
}

fn main() {
    if let Err(error) = run(env::args().skip(1).collect()) {
        eprintln!("error: {error}");
        std::process::exit(1);
    }
}

fn run(args: Vec<String>) -> Result<(), String> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let descriptors = normalized_descriptors()?;

    match args.as_slice() {
        [] => write_outputs(&root, &descriptors),
        [flag] if flag == "--check" => check_current(&root, &descriptors),
        [flag, baseline] if flag == "--check-against" => {
            check_current(&root, &descriptors)?;
            check_against_baseline(&descriptors, Path::new(baseline))
        }
        [flag] if flag == "--help" || flag == "-h" => {
            println!("Usage: novarocks-error-manifest [--check | --check-against <ledger>]");
            Ok(())
        }
        _ => Err("usage: novarocks-error-manifest [--check | --check-against <ledger>]".to_owned()),
    }
}

fn normalized_descriptors() -> Result<Vec<ErrorCodeDescriptor>, String> {
    let mut descriptors = ERROR_CODE_DESCRIPTORS.to_vec();
    descriptors.sort_by_key(|descriptor| descriptor.code);

    let mut codes = HashSet::new();
    for descriptor in &descriptors {
        let code = descriptor.code.as_str();
        if !is_code(code) {
            return Err(format!("invalid error code descriptor: {code}"));
        }
        if !codes.insert(code) {
            return Err(format!("duplicate error code descriptor: {code}"));
        }
    }
    Ok(descriptors)
}

fn is_code(code: &str) -> bool {
    let mut parts = code.split('.');
    let Some(first) = parts.next() else {
        return false;
    };
    if first.is_empty() || !is_code_segment(first) {
        return false;
    }
    let mut dotted = false;
    for part in parts {
        dotted = true;
        if part.is_empty() || !is_code_segment(part) {
            return false;
        }
    }
    dotted
}

fn is_code_segment(part: &str) -> bool {
    part.bytes()
        .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
}

fn write_outputs(root: &Path, descriptors: &[ErrorCodeDescriptor]) -> Result<(), String> {
    fs::write(root.join(MANIFEST_NAME), render_manifest(descriptors))
        .map_err(|error| format!("write {MANIFEST_NAME}: {error}"))?;
    fs::write(root.join(LEDGER_NAME), render_ledger(descriptors))
        .map_err(|error| format!("write {LEDGER_NAME}: {error}"))?;
    Ok(())
}

fn check_current(root: &Path, descriptors: &[ErrorCodeDescriptor]) -> Result<(), String> {
    check_file(
        &root.join(MANIFEST_NAME),
        &render_manifest(descriptors),
        MANIFEST_NAME,
    )?;
    check_file(
        &root.join(LEDGER_NAME),
        &render_ledger(descriptors),
        LEDGER_NAME,
    )
}

fn check_file(path: &Path, expected: &str, name: &str) -> Result<(), String> {
    let actual = fs::read_to_string(path).map_err(|error| format!("read {name}: {error}"))?;
    if actual == expected {
        Ok(())
    } else {
        Err(format!("{name} is stale; run novarocks-error-manifest"))
    }
}

fn render_manifest(descriptors: &[ErrorCodeDescriptor]) -> String {
    let mut output = format!("{HEADER}schema_version={SCHEMA_VERSION}\ncode\tphase\n");
    for descriptor in descriptors {
        output.push_str(descriptor.code.as_str());
        output.push('\t');
        output.push_str(phase_name(descriptor.phase));
        output.push('\n');
    }
    output
}

fn render_ledger(descriptors: &[ErrorCodeDescriptor]) -> String {
    let mut output = format!("{HEADER}schema_version={SCHEMA_VERSION}\ncode\tphase\tstatus\n");
    for descriptor in descriptors {
        output.push_str(descriptor.code.as_str());
        output.push('\t');
        output.push_str(phase_name(descriptor.phase));
        output.push('\t');
        output.push_str(status_name(descriptor.status));
        output.push('\n');
    }
    output
}

fn phase_name(phase: ErrorPhase) -> &'static str {
    match phase {
        ErrorPhase::Lex => "Lex",
        ErrorPhase::Parse => "Parse",
        ErrorPhase::Validate => "Validate",
        ErrorPhase::Analyze => "Analyze",
        ErrorPhase::Admit => "Admit",
    }
}

fn parse_phase(value: &str) -> Result<ErrorPhase, String> {
    match value {
        "Lex" => Ok(ErrorPhase::Lex),
        "Parse" => Ok(ErrorPhase::Parse),
        "Validate" => Ok(ErrorPhase::Validate),
        "Analyze" => Ok(ErrorPhase::Analyze),
        "Admit" => Ok(ErrorPhase::Admit),
        _ => Err(format!("invalid ledger phase: {value}")),
    }
}

fn status_name(status: ErrorCodeStatus) -> &'static str {
    match status {
        ErrorCodeStatus::Active => "Active",
        ErrorCodeStatus::Deprecated => "Deprecated",
    }
}

fn parse_status(value: &str) -> Result<ErrorCodeStatus, String> {
    match value {
        "Active" => Ok(ErrorCodeStatus::Active),
        "Deprecated" => Ok(ErrorCodeStatus::Deprecated),
        _ => Err(format!("invalid ledger status: {value}")),
    }
}

fn check_against_baseline(
    descriptors: &[ErrorCodeDescriptor],
    baseline_path: &Path,
) -> Result<(), String> {
    let baseline = parse_ledger(baseline_path)?;
    let current = descriptors
        .iter()
        .map(|descriptor| {
            (
                descriptor.code.as_str(),
                LedgerEntry {
                    phase: descriptor.phase,
                    status: descriptor.status,
                },
            )
        })
        .collect::<BTreeMap<_, _>>();

    for (code, previous) in baseline {
        let Some(next) = current.get(code.as_str()) else {
            return Err(format!("published error code removed: {code}"));
        };
        if next.phase != previous.phase {
            return Err(format!("published error code phase changed: {code}"));
        }
        if previous.status == ErrorCodeStatus::Deprecated
            && next.status != ErrorCodeStatus::Deprecated
        {
            return Err(format!("deprecated error code reactivated: {code}"));
        }
    }
    Ok(())
}

fn parse_ledger(path: &Path) -> Result<BTreeMap<String, LedgerEntry>, String> {
    let source = fs::read_to_string(path)
        .map_err(|error| format!("read baseline ledger {}: {error}", path.display()))?;
    let mut lines = source.lines().filter(|line| !line.starts_with('#'));
    let version = lines
        .next()
        .ok_or_else(|| format!("baseline ledger {} has no schema version", path.display()))?;
    if version == "schema_version=0" {
        if lines.next().is_some() {
            return Err("v0 baseline ledger must be empty".to_owned());
        }
        return Ok(BTreeMap::new());
    }
    if version != "schema_version=1" {
        return Err(format!("unsupported baseline ledger schema: {version}"));
    }
    if lines.next() != Some("code\tphase\tstatus") {
        return Err("baseline ledger has invalid header".to_owned());
    }

    let mut entries = BTreeMap::new();
    for line in lines.filter(|line| !line.is_empty()) {
        let mut fields = line.split('\t');
        let code = fields.next().unwrap_or_default();
        let phase = fields.next().unwrap_or_default();
        let status = fields.next().unwrap_or_default();
        if fields.next().is_some() || !is_code(code) {
            return Err(format!("invalid baseline ledger entry: {line}"));
        }
        let entry = LedgerEntry {
            phase: parse_phase(phase)?,
            status: parse_status(status)?,
        };
        if entries.insert(code.to_owned(), entry).is_some() {
            return Err(format!("duplicate baseline ledger code: {code}"));
        }
    }
    Ok(entries)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn baseline_path(name: &str) -> PathBuf {
        env::temp_dir().join(format!(
            "novarocks-error-manifest-{name}-{}.tsv",
            std::process::id()
        ))
    }

    #[test]
    fn manifest_and_ledger_are_deterministic() {
        let descriptors = normalized_descriptors().expect("parser descriptors are valid");
        assert!(render_manifest(&descriptors).contains("sql.parse.unsupported_statement\tParse"));
        assert!(render_ledger(&descriptors).contains("sql.lex.unterminated_string\tLex\tActive"));
    }

    #[test]
    fn baseline_rejects_phase_reassignment() {
        let path = baseline_path("phase");
        fs::write(
            &path,
            "schema_version=1\ncode\tphase\tstatus\nsql.parse.unsupported_statement\tLex\tActive\n",
        )
        .expect("write baseline");

        let error = check_against_baseline(&normalized_descriptors().expect("descriptors"), &path)
            .expect_err("phase change must fail");
        assert!(error.contains("phase changed"), "unexpected error: {error}");
        fs::remove_file(path).expect("remove baseline");
    }

    #[test]
    fn baseline_rejects_removed_codes() {
        let path = baseline_path("removed");
        fs::write(
            &path,
            "schema_version=1\ncode\tphase\tstatus\nsql.old.removed\tParse\tDeprecated\n",
        )
        .expect("write baseline");

        let error = check_against_baseline(&normalized_descriptors().expect("descriptors"), &path)
            .expect_err("removed published code must fail");
        assert!(error.contains("removed"), "unexpected error: {error}");
        fs::remove_file(path).expect("remove baseline");
    }
}
