// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
use std::{
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

const COMPAT_THRIFT_DIR: &str = "../../idl/compat/thrift";
const COMPAT_PROTO_DIR: &str = "../../idl/compat/proto";
const COMPAT_STAROS_DIR: &str = "../../idl/compat/staros";

fn find_tool(name: &str, thirdparty_bin: &Path) -> PathBuf {
    if name == "protoc" {
        let thirdparty_protoc = thirdparty_bin.join("protoc");
        if thirdparty_protoc.exists() {
            return thirdparty_protoc;
        }
    }
    let thirdparty_tool = thirdparty_bin.join(name);
    if thirdparty_tool.exists() {
        return thirdparty_tool;
    }
    which::which(name).unwrap_or(thirdparty_tool)
}

fn has_thirdparty_layout(path: &Path) -> bool {
    path.join("include").exists() && (path.join("lib").exists() || path.join("lib64").exists())
}

fn resolve_thirdparty_root(manifest_dir: &Path) -> Result<PathBuf, String> {
    let root = match env::var("STARROCKS_THIRDPARTY") {
        Ok(raw) if !raw.trim().is_empty() => {
            let configured = PathBuf::from(raw.trim());
            if configured.is_absolute() {
                configured
            } else {
                manifest_dir.join(configured)
            }
        }
        _ => manifest_dir.join("thirdparty"),
    };
    if !root.is_dir() {
        return Err(format!(
            "thirdparty directory not found. expected default '{}', or set STARROCKS_THIRDPARTY",
            root.display()
        ));
    }
    let installed = root.join("installed");
    if has_thirdparty_layout(&installed) {
        Ok(installed)
    } else {
        Err(format!(
            "thirdparty artifacts not found under '{}'. expected '<thirdparty-root>/installed/{{include,lib|lib64}}'. set STARROCKS_THIRDPARTY to thirdparty root",
            root.display()
        ))
    }
}

fn find_cxx_runtime(lib_name: &str) -> Option<PathBuf> {
    let mut candidates = Vec::new();
    if let Ok(cxx) = env::var("CXX")
        && !cxx.trim().is_empty()
    {
        candidates.push(cxx);
    }
    candidates.extend(["g++".to_string(), "c++".to_string()]);
    for compiler in candidates {
        let output = std::process::Command::new(&compiler)
            .arg(format!("-print-file-name={lib_name}"))
            .output();
        let Ok(output) = output else {
            continue;
        };
        if !output.status.success() {
            continue;
        }
        let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
        if path.is_empty() || path == lib_name {
            continue;
        }
        let path = PathBuf::from(path);
        if path.exists() {
            return Some(path);
        }
    }
    None
}

fn idl_path(dir: &str, file: &str) -> PathBuf {
    Path::new(dir).join(file)
}

fn print_rerun_files(dir: &str, files: &[&str]) {
    for file in files {
        println!("cargo:rerun-if-changed={}", idl_path(dir, file).display());
    }
}

fn validate_thrift_rs_namespaces() {
    let mut entries = fs::read_dir(COMPAT_THRIFT_DIR)
        .expect("read compat thrift dir")
        .map(|entry| entry.expect("read thrift dir entry").path())
        .filter(|path| path.extension().and_then(|value| value.to_str()) == Some("thrift"))
        .collect::<Vec<_>>();
    entries.sort();
    let mut missing = Vec::new();
    for path in entries {
        println!("cargo:rerun-if-changed={}", path.display());
        let contents = fs::read_to_string(&path).expect("read thrift source");
        if !contents
            .lines()
            .any(|line| line.trim() == "namespace rs thrift")
        {
            missing.push(path.display().to_string());
        }
    }
    if !missing.is_empty() {
        panic!(
            "thrift files missing `namespace rs thrift`: {}",
            missing.join(", ")
        );
    }
}

fn emit_proto_root_mod(out_dir: &Path) {
    fs::write(
        out_dir.join("proto_root_mod.rs"),
        r#"// @generated by build.rs
pub(crate) mod proto {
    pub mod starrocks {
        #![allow(clippy::doc_lazy_continuation, clippy::len_without_is_empty)]
        tonic::include_proto!("starrocks");
    }

    pub mod staros {
        tonic::include_proto!("staros");
    }
}
"#,
    )
    .expect("write proto_root_mod.rs");
}

fn patch_plan_nodes_rs(thrift_rs_out: &Path) {
    let path = thrift_rs_out.join("plan_nodes.rs");
    let Ok(mut contents) = fs::read_to_string(&path) else {
        return;
    };
    let broken = "pub const : TPlanNodeType = TPlanNodeType(39);";
    if contents.contains(broken) {
        contents = contents.replace(
            broken,
            "pub const RAW_VALUES_NODE: TPlanNodeType = TPlanNodeType(39);",
        );
        fs::write(path, contents).expect("patch plan_nodes.rs");
    }
}

fn main() {
    println!("cargo:rerun-if-env-changed=STARROCKS_THIRDPARTY");
    println!("cargo:rerun-if-env-changed=STARROCKS_GCC_HOME");
    println!("cargo:rerun-if-changed=src/shim/compat.cpp");
    println!("cargo:rerun-if-changed=src/shim/compat.h");
    println!("cargo:rerun-if-changed=src/shim/brpc_server.cpp");
    print_rerun_files(
        COMPAT_THRIFT_DIR,
        &[
            "HeartbeatService.thrift",
            "BackendService.thrift",
            "InternalService.thrift",
            "FrontendService.thrift",
            "Data.thrift",
            "Planner.thrift",
            "PlanNodes.thrift",
            "DataSinks.thrift",
            "Exprs.thrift",
            "Opcodes.thrift",
            "Status.thrift",
            "StatusCode.thrift",
            "Types.thrift",
            "AgentService.thrift",
            "StarrocksExternalService.thrift",
            "Descriptors.thrift",
        ],
    );
    print_rerun_files(
        COMPAT_PROTO_DIR,
        &[
            "internal_service.proto",
            "data.proto",
            "status.proto",
            "types.proto",
            "binlog.proto",
            "descriptors.proto",
            "olap_common.proto",
            "olap_file.proto",
            "lake_types.proto",
            "lake_service.proto",
            "tablet_schema.proto",
        ],
    );
    print_rerun_files(
        COMPAT_STAROS_DIR,
        &[
            "starlet.proto",
            "manager.proto",
            "service.proto",
            "star_status.proto",
            "file_store.proto",
            "shard.proto",
            "worker.proto",
        ],
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let thirdparty = resolve_thirdparty_root(&manifest_dir).unwrap_or_else(|error| {
        eprintln!("Error: {error}");
        eprintln!("  To build default thirdparty, run: ./thirdparty/build-thirdparty.sh");
        panic!("novarocks-compat requires STARROCKS_THIRDPARTY")
    });
    let thirdparty_bin = thirdparty.join("bin");
    let thirdparty_include = thirdparty.join("include");
    let thirdparty_lib = thirdparty.join("lib");
    let thirdparty_lib64 = thirdparty.join("lib64");
    let target = env::var("TARGET").unwrap_or_default();
    let is_macos = target.contains("apple") || target.contains("darwin");
    let is_linux = target.contains("linux");

    let thrift_out = out_dir.join("thrift");
    let cpp_proto_out = out_dir.join("proto");
    let thrift_rs_out = out_dir.join("thrift_rs");
    fs::create_dir_all(&thrift_out).expect("create thrift out dir");
    fs::create_dir_all(&cpp_proto_out).expect("create proto out dir");
    fs::create_dir_all(&thrift_rs_out).expect("create thrift_rs out dir");
    validate_thrift_rs_namespaces();

    let thrift = find_tool("thrift", &thirdparty_bin);
    for thrift_file in ["HeartbeatService.thrift", "InternalService.thrift"] {
        let thrift_path = idl_path(COMPAT_THRIFT_DIR, thrift_file);
        let status = std::process::Command::new(&thrift)
            .args(["-r", "-I", COMPAT_THRIFT_DIR, "--gen", "cpp", "-out"])
            .arg(&thrift_out)
            .arg(&thrift_path)
            .status()
            .expect("run thrift");
        if !status.success() {
            panic!(
                "thrift codegen failed for {} with status={status}",
                thrift_path.display()
            );
        }
    }
    for thrift_file in [
        "InternalService.thrift",
        "FrontendService.thrift",
        "HeartbeatService.thrift",
        "BackendService.thrift",
    ] {
        let thrift_path = idl_path(COMPAT_THRIFT_DIR, thrift_file);
        let status = std::process::Command::new(&thrift)
            .args(["-r", "-I", COMPAT_THRIFT_DIR, "--gen", "rs", "-out"])
            .arg(&thrift_rs_out)
            .arg(&thrift_path)
            .status()
            .expect("run thrift --gen rs");
        if !status.success() {
            panic!(
                "thrift rs codegen failed for {} with status={status}",
                thrift_path.display()
            );
        }
    }
    patch_plan_nodes_rs(&thrift_rs_out);
    let mut module_files = fs::read_dir(&thrift_rs_out)
        .expect("read thrift_rs out dir")
        .map(|entry| entry.expect("thrift_rs entry").path())
        .filter(|path| path.extension().and_then(|value| value.to_str()) == Some("rs"))
        .collect::<Vec<_>>();
    module_files.sort();
    let mut thrift_root = String::from("// @generated by build.rs\npub(crate) mod thrift {\n");
    for path in module_files {
        let stem = path
            .file_stem()
            .and_then(|value| value.to_str())
            .expect("module name");
        let canonical = path.canonicalize().expect("canonicalize thrift module");
        let _ = writeln!(
            thrift_root,
            "    #[allow(unreachable_patterns, unused_variables)]"
        );
        let _ = writeln!(
            thrift_root,
            "    #[path = {:?}]\n    pub mod {};\n",
            canonical, stem
        );
    }
    thrift_root.push_str("}\n");
    fs::write(out_dir.join("thrift_root_mod.rs"), thrift_root).expect("write thrift root");

    let cpp_protos = [
        "status.proto",
        "types.proto",
        "data.proto",
        "binlog.proto",
        "olap_common.proto",
        "tablet_schema.proto",
        "olap_file.proto",
        "descriptors.proto",
        "lake_types.proto",
        "lake_service.proto",
        "internal_service.proto",
    ]
    .map(|file| idl_path(COMPAT_PROTO_DIR, file));
    let mut protoc = std::process::Command::new(find_tool("protoc", &thirdparty_bin));
    protoc
        .arg("-I")
        .arg(COMPAT_PROTO_DIR)
        .arg("--cpp_out")
        .arg(&cpp_proto_out);
    for file in &cpp_protos {
        protoc.arg(file);
    }
    let status = protoc.status().expect("run protoc");
    if !status.success() {
        panic!("protoc codegen failed with status={status}");
    }

    let mut build = cc::Build::new();
    build
        .cpp(true)
        .file("src/shim/compat.cpp")
        .file("src/shim/brpc_server.cpp");
    for directory in [&thrift_out, &cpp_proto_out] {
        for entry in fs::read_dir(directory).expect("read generated c++ dir") {
            let path = entry.expect("generated c++ entry").path();
            let is_source = matches!(
                path.extension().and_then(|value| value.to_str()),
                Some("cpp") | Some("cc")
            );
            let is_skeleton = path
                .file_name()
                .and_then(|value| value.to_str())
                .is_some_and(|name| name.ends_with(".skeleton.cpp"));
            if is_source && !is_skeleton {
                build.file(path);
            }
        }
    }
    build
        .flag_if_supported("-std=c++17")
        .flag_if_supported("-Wno-deprecated-declarations")
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-vla-cxx-extension")
        .flag_if_supported("-w")
        .define("GLOG_USE_GLOG_EXPORT", None)
        .define("GLOG_STATIC_DEFINE", None)
        .include("src/shim")
        .include(&thrift_out)
        .include(&cpp_proto_out)
        .include(&thirdparty_include);
    if is_linux {
        build.cpp_link_stdlib(None).cpp_link_stdlib_static(false);
    }
    if is_macos {
        build
            .include("/opt/homebrew/opt/openssl/include")
            .include("/opt/homebrew/include");
    }
    build.compile("novarocks_compat");

    println!(
        "cargo:rustc-link-search=native={}",
        thirdparty_lib.display()
    );
    if thirdparty_lib64.exists() {
        println!(
            "cargo:rustc-link-search=native={}",
            thirdparty_lib64.display()
        );
    }
    if is_linux {
        let libstdcpp = find_cxx_runtime("libstdc++.a")
            .unwrap_or_else(|| panic!("libstdc++.a not found; static C++ runtime is required"));
        println!(
            "cargo:rustc-link-search=native={}",
            libstdcpp.parent().expect("libstdc++ parent").display()
        );
        println!("cargo:rustc-link-arg=-static-libstdc++");
        println!("cargo:rustc-link-arg=-static-libgcc");
        println!("cargo:rustc-link-lib=static=stdc++");
        if let Some(libsupcxx) = find_cxx_runtime("libsupc++.a") {
            println!(
                "cargo:rustc-link-search=native={}",
                libsupcxx.parent().expect("libsupc++ parent").display()
            );
            println!("cargo:rustc-link-lib=static=supc++");
        }
        println!(
            "cargo:rustc-link-arg=-Wl,-rpath,{}",
            thirdparty_lib.display()
        );
        if thirdparty_lib64.exists() {
            println!(
                "cargo:rustc-link-arg=-Wl,-rpath,{}",
                thirdparty_lib64.display()
            );
        }
    }
    for library in ["ssl", "crypto"] {
        println!("cargo:rustc-link-lib={library}");
    }
    for library in ["brpc", "protobuf", "glog", "leveldb", "gflags", "thrift"] {
        println!("cargo:rustc-link-lib=static={library}");
    }
    println!("cargo:rustc-link-lib=z");
    if is_macos {
        println!("cargo:rustc-link-arg=-Wl,-U,_MallocExtension_ReleaseFreeMemory");
        println!("cargo:rustc-link-arg=-Wl,-U,_ProfilerStart");
        println!("cargo:rustc-link-arg=-Wl,-U,_ProfilerStop");
        println!("cargo:rustc-link-arg=-Wl,-U,__Z13GetStackTracePPvii");
        println!("cargo:rustc-link-lib=objc");
        println!("cargo:rustc-link-lib=framework=Foundation");
    }
    println!("cargo:rustc-link-lib=pthread");

    let protoc = protoc_bin_vendored::protoc_bin_path().expect("vendored protoc path");
    unsafe { env::set_var("PROTOC", protoc) };
    let starrocks_protos = [
        "status.proto",
        "types.proto",
        "data.proto",
        "binlog.proto",
        "olap_common.proto",
        "tablet_schema.proto",
        "olap_file.proto",
        "descriptors.proto",
        "lake_types.proto",
        "lake_service.proto",
        "internal_service.proto",
    ]
    .map(|file| idl_path(COMPAT_PROTO_DIR, file));
    tonic_build::configure()
        .build_client(true)
        .build_server(true)
        .compile_protos(&starrocks_protos, &[COMPAT_PROTO_DIR])
        .expect("compile StarRocks compat protos");
    let staros_protos =
        ["starlet.proto", "manager.proto"].map(|file| idl_path(COMPAT_STAROS_DIR, file));
    tonic_build::configure()
        .build_client(true)
        .build_server(true)
        .compile_protos(&staros_protos, &[COMPAT_STAROS_DIR])
        .expect("compile StarOS protos");
    emit_proto_root_mod(&out_dir);
}
