// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

use crate::Span;

/// A source token, including trivia, with its exact original byte range.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub const fn new(kind: TokenKind, span: Span) -> Self {
        Self { kind, span }
    }
}

/// The lexical category of a token.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TokenKind {
    Keyword(Keyword),
    Ident,
    QuotedIdent,
    UserVariable,
    String,
    Number,
    HexNumber,
    Symbol(Symbol),
    Trivia(TriviaKind),
    End,
}

/// Structured source trivia preserved in the token stream.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TriviaKind {
    Whitespace,
    LineComment,
    BlockComment,
    HintComment,
}

/// Keywords recognized by the MySQL/StarRocks grammar.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Keyword {
    Add,
    Alter,
    Analyze,
    And,
    Anti,
    Any,
    Array,
    As,
    Asc,
    At,
    Async,
    Backend,
    Backends,
    Basic,
    Between,
    Branch,
    Buckets,
    By,
    Call,
    Cancel,
    Catalog,
    Case,
    Cast,
    Collate,
    Column,
    Columns,
    Comment,
    Costs,
    Create,
    Cross,
    Cube,
    Current,
    Database,
    Date,
    Default,
    Desc,
    Distinct,
    Drop,
    Else,
    End,
    Escape,
    Except,
    Exists,
    Expire,
    Explain,
    External,
    False,
    Fetch,
    Files,
    Filter,
    First,
    Following,
    For,
    Force,
    From,
    Full,
    Group,
    Grouping,
    Groups,
    Having,
    Histogram,
    If,
    Ignore,
    Ilike,
    In,
    Inner,
    Intersect,
    Interval,
    Is,
    Jobs,
    Join,
    Kill,
    Lateral,
    Last,
    Left,
    Like,
    Limit,
    Logical,
    Manifests,
    Materialized,
    Meta,
    Natural,
    Next,
    Not,
    Null,
    Nulls,
    Of,
    Offset,
    On,
    Only,
    Order,
    Ordinality,
    Or,
    Orphan,
    Outer,
    Over,
    Partition,
    Position,
    Preceding,
    Percent,
    Properties,
    Qualify,
    Range,
    Recursive,
    Refresh,
    Remove,
    Respect,
    Rewrite,
    Right,
    Rlike,
    Rollup,
    Row,
    Rows,
    Sample,
    Select,
    Semi,
    Set,
    Sets,
    Show,
    Similar,
    Some,
    Snapshots,
    Stats,
    Struct,
    Substring,
    Sync,
    System,
    SystemTime,
    Table,
    Tables,
    Tag,
    Then,
    Time,
    Timestamp,
    Ties,
    To,
    True,
    Truncate,
    TryCast,
    Unbounded,
    Union,
    Unnest,
    Unset,
    Using,
    Verbose,
    Version,
    View,
    Views,
    With,
    When,
    Where,
    Window,
    Within,
    Values,
    Zone,
}

/// Punctuation and operators recognized by the foundation lexer.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Symbol {
    Ampersand,
    DoubleAmpersand,
    Bang,
    Backslash,
    Caret,
    Colon,
    ColonEq,
    DoubleColon,
    Comma,
    Dot,
    DoubleDot,
    Eq,
    FatArrow,
    Gt,
    Gte,
    LBrace,
    LBracket,
    LParen,
    Lte,
    Lt,
    ShiftLeft,
    Minus,
    Neq,
    NullSafeEq,
    Percent,
    Pipe,
    DoublePipe,
    Plus,
    Question,
    RBrace,
    RBracket,
    RParen,
    Semicolon,
    Slash,
    Star,
    Tilde,
    Arrow,
    LongArrow,
    ShiftRight,
    QuestionAmpersand,
}

impl Symbol {
    pub const fn sql(self) -> &'static str {
        match self {
            Self::Ampersand => "&",
            Self::DoubleAmpersand => "&&",
            Self::Bang => "!",
            Self::Backslash => "\\",
            Self::Caret => "^",
            Self::Colon => ":",
            Self::ColonEq => ":=",
            Self::DoubleColon => "::",
            Self::Comma => ",",
            Self::Dot => ".",
            Self::DoubleDot => "..",
            Self::Eq => "=",
            Self::FatArrow => "=>",
            Self::Gt => ">",
            Self::Gte => ">=",
            Self::LBrace => "{",
            Self::LBracket => "[",
            Self::LParen => "(",
            Self::Lte => "<=",
            Self::Lt => "<",
            Self::ShiftLeft => "<<",
            Self::Minus => "-",
            Self::Neq => "!=",
            Self::NullSafeEq => "<=>",
            Self::Percent => "%",
            Self::Pipe => "|",
            Self::DoublePipe => "||",
            Self::Plus => "+",
            Self::Question => "?",
            Self::RBrace => "}",
            Self::RBracket => "]",
            Self::RParen => ")",
            Self::Semicolon => ";",
            Self::Slash => "/",
            Self::Star => "*",
            Self::Tilde => "~",
            Self::Arrow => "->",
            Self::LongArrow => "->>",
            Self::ShiftRight => ">>",
            Self::QuestionAmpersand => "?&",
        }
    }
}
