-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--   http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- @sequential=true
-- @order_sensitive=true
-- @tags=iceberg,metadata_depth,native_depth64
-- Native CTAS, INSERT SELECT and SELECT of non-NULL values whose
-- type has logical depth 64 (63 struct containers plus an INT leaf), and a
-- 65-level column refused by DDL without effect. Generated by
-- tests/sql/fixtures/uea7b3-native-depth64/generate.py; expected values are
-- derived from the fixed inputs, never recorded.

-- query 1
-- @skip_result_check=true
CREATE EXTERNAL CATALOG nativedepth64_${uuid0}
PROPERTIES (
  "type" = "iceberg",
  "iceberg.catalog.type" = "hadoop",
  "iceberg.catalog.warehouse" = "${iceberg_test_warehouse}/native_depth64_${uuid0}",
  "aws.s3.endpoint" = "${oss_endpoint}",
  "credential.object-store-metadata.consumer-role" = "frontend",
  "credential.object-store-metadata.mode" = "static",
  "credential.object-store-metadata.name" = "${iceberg_object_store_credential_name}",
  "credential.object-store-metadata.generation" = "${iceberg_object_store_credential_generation}",
  "credential.object-store-data.consumer-role" = "backend",
  "credential.object-store-data.mode" = "static",
  "credential.object-store-data.name" = "${iceberg_object_store_credential_name}",
  "credential.object-store-data.generation" = "${iceberg_object_store_credential_generation}",
  "aws.s3.region" = "us-east-1",
  "aws.s3.enable_path_style_access" = "true"
);
CREATE DATABASE nativedepth64_${uuid0}.ns_${uuid0};
SET CATALOG nativedepth64_${uuid0};
USE ns_${uuid0};

-- query 2
-- @skip_result_check=true
CREATE TABLE deep_values (id BIGINT, deep STRUCT<n1 STRUCT<n2 STRUCT<n3 STRUCT<n4 STRUCT<n5 STRUCT<n6 STRUCT<n7 STRUCT<n8 STRUCT<n9 STRUCT<n10 STRUCT<n11 STRUCT<n12 STRUCT<n13 STRUCT<n14 STRUCT<n15 STRUCT<n16 STRUCT<n17 STRUCT<n18 STRUCT<n19 STRUCT<n20 STRUCT<n21 STRUCT<n22 STRUCT<n23 STRUCT<n24 STRUCT<n25 STRUCT<n26 STRUCT<n27 STRUCT<n28 STRUCT<n29 STRUCT<n30 STRUCT<n31 STRUCT<n32 STRUCT<n33 STRUCT<n34 STRUCT<n35 STRUCT<n36 STRUCT<n37 STRUCT<n38 STRUCT<n39 STRUCT<n40 STRUCT<n41 STRUCT<n42 STRUCT<n43 STRUCT<n44 STRUCT<n45 STRUCT<n46 STRUCT<n47 STRUCT<n48 STRUCT<n49 STRUCT<n50 STRUCT<n51 STRUCT<n52 STRUCT<n53 STRUCT<n54 STRUCT<n55 STRUCT<n56 STRUCT<n57 STRUCT<n58 STRUCT<n59 STRUCT<n60 STRUCT<n61 STRUCT<n62 STRUCT<n63 INT>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>)
TBLPROPERTIES ("format-version"="3");

-- query 3
-- @skip_result_check=true
CREATE TABLE seed (id BIGINT, leaf INT);
INSERT INTO seed VALUES (1, 7), (3, -5);

-- query 4
-- @skip_result_check=true
CREATE TABLE lvl63 AS SELECT id, named_struct('n63', leaf) AS v FROM seed;

-- query 5
-- @skip_result_check=true
CREATE TABLE lvl62 AS SELECT id, named_struct('n62', v) AS v FROM lvl63;

-- query 6
-- @skip_result_check=true
CREATE TABLE lvl61 AS SELECT id, named_struct('n61', v) AS v FROM lvl62;

-- query 7
-- @skip_result_check=true
CREATE TABLE lvl60 AS SELECT id, named_struct('n60', v) AS v FROM lvl61;

-- query 8
-- @skip_result_check=true
CREATE TABLE lvl59 AS SELECT id, named_struct('n59', v) AS v FROM lvl60;

-- query 9
-- @skip_result_check=true
CREATE TABLE lvl58 AS SELECT id, named_struct('n58', v) AS v FROM lvl59;

-- query 10
-- @skip_result_check=true
CREATE TABLE lvl57 AS SELECT id, named_struct('n57', v) AS v FROM lvl58;

-- query 11
-- @skip_result_check=true
CREATE TABLE lvl56 AS SELECT id, named_struct('n56', v) AS v FROM lvl57;

-- query 12
-- @skip_result_check=true
CREATE TABLE lvl55 AS SELECT id, named_struct('n55', v) AS v FROM lvl56;

-- query 13
-- @skip_result_check=true
CREATE TABLE lvl54 AS SELECT id, named_struct('n54', v) AS v FROM lvl55;

-- query 14
-- @skip_result_check=true
CREATE TABLE lvl53 AS SELECT id, named_struct('n53', v) AS v FROM lvl54;

-- query 15
-- @skip_result_check=true
CREATE TABLE lvl52 AS SELECT id, named_struct('n52', v) AS v FROM lvl53;

-- query 16
-- @skip_result_check=true
CREATE TABLE lvl51 AS SELECT id, named_struct('n51', v) AS v FROM lvl52;

-- query 17
-- @skip_result_check=true
CREATE TABLE lvl50 AS SELECT id, named_struct('n50', v) AS v FROM lvl51;

-- query 18
-- @skip_result_check=true
CREATE TABLE lvl49 AS SELECT id, named_struct('n49', v) AS v FROM lvl50;

-- query 19
-- @skip_result_check=true
CREATE TABLE lvl48 AS SELECT id, named_struct('n48', v) AS v FROM lvl49;

-- query 20
-- @skip_result_check=true
CREATE TABLE lvl47 AS SELECT id, named_struct('n47', v) AS v FROM lvl48;

-- query 21
-- @skip_result_check=true
CREATE TABLE lvl46 AS SELECT id, named_struct('n46', v) AS v FROM lvl47;

-- query 22
-- @skip_result_check=true
CREATE TABLE lvl45 AS SELECT id, named_struct('n45', v) AS v FROM lvl46;

-- query 23
-- @skip_result_check=true
CREATE TABLE lvl44 AS SELECT id, named_struct('n44', v) AS v FROM lvl45;

-- query 24
-- @skip_result_check=true
CREATE TABLE lvl43 AS SELECT id, named_struct('n43', v) AS v FROM lvl44;

-- query 25
-- @skip_result_check=true
CREATE TABLE lvl42 AS SELECT id, named_struct('n42', v) AS v FROM lvl43;

-- query 26
-- @skip_result_check=true
CREATE TABLE lvl41 AS SELECT id, named_struct('n41', v) AS v FROM lvl42;

-- query 27
-- @skip_result_check=true
CREATE TABLE lvl40 AS SELECT id, named_struct('n40', v) AS v FROM lvl41;

-- query 28
-- @skip_result_check=true
CREATE TABLE lvl39 AS SELECT id, named_struct('n39', v) AS v FROM lvl40;

-- query 29
-- @skip_result_check=true
CREATE TABLE lvl38 AS SELECT id, named_struct('n38', v) AS v FROM lvl39;

-- query 30
-- @skip_result_check=true
CREATE TABLE lvl37 AS SELECT id, named_struct('n37', v) AS v FROM lvl38;

-- query 31
-- @skip_result_check=true
CREATE TABLE lvl36 AS SELECT id, named_struct('n36', v) AS v FROM lvl37;

-- query 32
-- @skip_result_check=true
CREATE TABLE lvl35 AS SELECT id, named_struct('n35', v) AS v FROM lvl36;

-- query 33
-- @skip_result_check=true
CREATE TABLE lvl34 AS SELECT id, named_struct('n34', v) AS v FROM lvl35;

-- query 34
-- @skip_result_check=true
CREATE TABLE lvl33 AS SELECT id, named_struct('n33', v) AS v FROM lvl34;

-- query 35
-- @skip_result_check=true
CREATE TABLE lvl32 AS SELECT id, named_struct('n32', v) AS v FROM lvl33;

-- query 36
-- @skip_result_check=true
CREATE TABLE lvl31 AS SELECT id, named_struct('n31', v) AS v FROM lvl32;

-- query 37
-- @skip_result_check=true
CREATE TABLE lvl30 AS SELECT id, named_struct('n30', v) AS v FROM lvl31;

-- query 38
-- @skip_result_check=true
CREATE TABLE lvl29 AS SELECT id, named_struct('n29', v) AS v FROM lvl30;

-- query 39
-- @skip_result_check=true
CREATE TABLE lvl28 AS SELECT id, named_struct('n28', v) AS v FROM lvl29;

-- query 40
-- @skip_result_check=true
CREATE TABLE lvl27 AS SELECT id, named_struct('n27', v) AS v FROM lvl28;

-- query 41
-- @skip_result_check=true
CREATE TABLE lvl26 AS SELECT id, named_struct('n26', v) AS v FROM lvl27;

-- query 42
-- @skip_result_check=true
CREATE TABLE lvl25 AS SELECT id, named_struct('n25', v) AS v FROM lvl26;

-- query 43
-- @skip_result_check=true
CREATE TABLE lvl24 AS SELECT id, named_struct('n24', v) AS v FROM lvl25;

-- query 44
-- @skip_result_check=true
CREATE TABLE lvl23 AS SELECT id, named_struct('n23', v) AS v FROM lvl24;

-- query 45
-- @skip_result_check=true
CREATE TABLE lvl22 AS SELECT id, named_struct('n22', v) AS v FROM lvl23;

-- query 46
-- @skip_result_check=true
CREATE TABLE lvl21 AS SELECT id, named_struct('n21', v) AS v FROM lvl22;

-- query 47
-- @skip_result_check=true
CREATE TABLE lvl20 AS SELECT id, named_struct('n20', v) AS v FROM lvl21;

-- query 48
-- @skip_result_check=true
CREATE TABLE lvl19 AS SELECT id, named_struct('n19', v) AS v FROM lvl20;

-- query 49
-- @skip_result_check=true
CREATE TABLE lvl18 AS SELECT id, named_struct('n18', v) AS v FROM lvl19;

-- query 50
-- @skip_result_check=true
CREATE TABLE lvl17 AS SELECT id, named_struct('n17', v) AS v FROM lvl18;

-- query 51
-- @skip_result_check=true
CREATE TABLE lvl16 AS SELECT id, named_struct('n16', v) AS v FROM lvl17;

-- query 52
-- @skip_result_check=true
CREATE TABLE lvl15 AS SELECT id, named_struct('n15', v) AS v FROM lvl16;

-- query 53
-- @skip_result_check=true
CREATE TABLE lvl14 AS SELECT id, named_struct('n14', v) AS v FROM lvl15;

-- query 54
-- @skip_result_check=true
CREATE TABLE lvl13 AS SELECT id, named_struct('n13', v) AS v FROM lvl14;

-- query 55
-- @skip_result_check=true
CREATE TABLE lvl12 AS SELECT id, named_struct('n12', v) AS v FROM lvl13;

-- query 56
-- @skip_result_check=true
CREATE TABLE lvl11 AS SELECT id, named_struct('n11', v) AS v FROM lvl12;

-- query 57
-- @skip_result_check=true
CREATE TABLE lvl10 AS SELECT id, named_struct('n10', v) AS v FROM lvl11;

-- query 58
-- @skip_result_check=true
CREATE TABLE lvl9 AS SELECT id, named_struct('n9', v) AS v FROM lvl10;

-- query 59
-- @skip_result_check=true
CREATE TABLE lvl8 AS SELECT id, named_struct('n8', v) AS v FROM lvl9;

-- query 60
-- @skip_result_check=true
CREATE TABLE lvl7 AS SELECT id, named_struct('n7', v) AS v FROM lvl8;

-- query 61
-- @skip_result_check=true
CREATE TABLE lvl6 AS SELECT id, named_struct('n6', v) AS v FROM lvl7;

-- query 62
-- @skip_result_check=true
CREATE TABLE lvl5 AS SELECT id, named_struct('n5', v) AS v FROM lvl6;

-- query 63
-- @skip_result_check=true
CREATE TABLE lvl4 AS SELECT id, named_struct('n4', v) AS v FROM lvl5;

-- query 64
-- @skip_result_check=true
CREATE TABLE lvl3 AS SELECT id, named_struct('n3', v) AS v FROM lvl4;

-- query 65
-- @skip_result_check=true
CREATE TABLE lvl2 AS SELECT id, named_struct('n2', v) AS v FROM lvl3;

-- query 66
-- @skip_result_check=true
CREATE TABLE lvl1 AS SELECT id, named_struct('n1', v) AS v FROM lvl2;

-- query 67
-- @skip_result_check=true
INSERT INTO deep_values SELECT id, v FROM lvl1;
INSERT INTO deep_values VALUES (2, NULL);

-- query 68
SELECT id, deep FROM deep_values ORDER BY id;

-- query 69
SELECT typeof(deep.n1.n2.n3.n4.n5.n6.n7.n8.n9.n10.n11.n12.n13.n14.n15.n16.n17.n18.n19.n20.n21.n22.n23.n24.n25.n26.n27.n28.n29.n30.n31.n32.n33.n34.n35.n36.n37.n38.n39.n40.n41.n42.n43.n44.n45.n46.n47.n48.n49.n50.n51.n52.n53.n54.n55.n56.n57.n58.n59.n60.n61.n62.n63) AS leaf_type, count(*) AS row_count FROM deep_values;

-- query 70
-- @skip_result_check=true
INSERT INTO deep_values SELECT id + 10, deep FROM deep_values WHERE id = 1;

-- query 71
-- @skip_result_check=true
CREATE TABLE deep_copy AS SELECT id, deep FROM deep_values;

-- query 72
SELECT id, deep FROM deep_copy ORDER BY id;

-- query 73
SELECT count(*) AS total, count(deep) AS non_null FROM deep_copy;

-- query 74
SELECT count(*) AS snapshot_count FROM deep_values$snapshots;

-- query 75
-- @expect_error=DDL type exceeds its node or depth budget
CREATE TABLE too_deep (id BIGINT, deep STRUCT<n1 STRUCT<n2 STRUCT<n3 STRUCT<n4 STRUCT<n5 STRUCT<n6 STRUCT<n7 STRUCT<n8 STRUCT<n9 STRUCT<n10 STRUCT<n11 STRUCT<n12 STRUCT<n13 STRUCT<n14 STRUCT<n15 STRUCT<n16 STRUCT<n17 STRUCT<n18 STRUCT<n19 STRUCT<n20 STRUCT<n21 STRUCT<n22 STRUCT<n23 STRUCT<n24 STRUCT<n25 STRUCT<n26 STRUCT<n27 STRUCT<n28 STRUCT<n29 STRUCT<n30 STRUCT<n31 STRUCT<n32 STRUCT<n33 STRUCT<n34 STRUCT<n35 STRUCT<n36 STRUCT<n37 STRUCT<n38 STRUCT<n39 STRUCT<n40 STRUCT<n41 STRUCT<n42 STRUCT<n43 STRUCT<n44 STRUCT<n45 STRUCT<n46 STRUCT<n47 STRUCT<n48 STRUCT<n49 STRUCT<n50 STRUCT<n51 STRUCT<n52 STRUCT<n53 STRUCT<n54 STRUCT<n55 STRUCT<n56 STRUCT<n57 STRUCT<n58 STRUCT<n59 STRUCT<n60 STRUCT<n61 STRUCT<n62 STRUCT<n63 STRUCT<n64 INT>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>);

-- query 76
SELECT count(*) AS snapshot_count FROM deep_values$snapshots;

-- query 77
-- @cleanup=true
-- @skip_result_check=true
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl1 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl2 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl3 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl4 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl5 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl6 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl7 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl8 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl9 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl10 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl11 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl12 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl13 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl14 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl15 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl16 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl17 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl18 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl19 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl20 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl21 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl22 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl23 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl24 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl25 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl26 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl27 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl28 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl29 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl30 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl31 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl32 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl33 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl34 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl35 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl36 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl37 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl38 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl39 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl40 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl41 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl42 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl43 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl44 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl45 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl46 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl47 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl48 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl49 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl50 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl51 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl52 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl53 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl54 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl55 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl56 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl57 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl58 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl59 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl60 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl61 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl62 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.lvl63 FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.seed FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.deep_copy FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.deep_values FORCE;
DROP DATABASE nativedepth64_${uuid0}.ns_${uuid0};
DROP CATALOG nativedepth64_${uuid0};
