-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--   http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- @sequential=true
-- @order_sensitive=true
-- @tags=iceberg,metadata_depth,native_depth64
-- Native INSERT, INSERT SELECT, CTAS and SELECT of non-NULL values whose
-- type has logical depth 64 (63 struct containers plus an INT leaf), and a
-- 65-level column refused by DDL without effect. Generated by
-- tests/sql/fixtures/uea7b3-native-depth64/generate.py; expected values are
-- derived from the fixed inputs, never recorded.

-- query 1
-- @skip_result_check=true
CREATE EXTERNAL CATALOG nativedepth64_${uuid0}
PROPERTIES (
  "type" = "iceberg",
  "iceberg.catalog.type" = "hadoop",
  "iceberg.catalog.warehouse" = "${iceberg_test_warehouse}/native_depth64_${uuid0}",
  "aws.s3.endpoint" = "${oss_endpoint}",
  "credential.object-store-metadata.consumer-role" = "frontend",
  "credential.object-store-metadata.mode" = "static",
  "credential.object-store-metadata.name" = "${iceberg_object_store_credential_name}",
  "credential.object-store-metadata.generation" = "${iceberg_object_store_credential_generation}",
  "credential.object-store-data.consumer-role" = "backend",
  "credential.object-store-data.mode" = "static",
  "credential.object-store-data.name" = "${iceberg_object_store_credential_name}",
  "credential.object-store-data.generation" = "${iceberg_object_store_credential_generation}",
  "aws.s3.region" = "us-east-1",
  "aws.s3.enable_path_style_access" = "true"
);
CREATE DATABASE nativedepth64_${uuid0}.ns_${uuid0};
SET CATALOG nativedepth64_${uuid0};
USE ns_${uuid0};

-- query 2
-- @skip_result_check=true
CREATE TABLE deep_values (id BIGINT, deep STRUCT<n1 STRUCT<n2 STRUCT<n3 STRUCT<n4 STRUCT<n5 STRUCT<n6 STRUCT<n7 STRUCT<n8 STRUCT<n9 STRUCT<n10 STRUCT<n11 STRUCT<n12 STRUCT<n13 STRUCT<n14 STRUCT<n15 STRUCT<n16 STRUCT<n17 STRUCT<n18 STRUCT<n19 STRUCT<n20 STRUCT<n21 STRUCT<n22 STRUCT<n23 STRUCT<n24 STRUCT<n25 STRUCT<n26 STRUCT<n27 STRUCT<n28 STRUCT<n29 STRUCT<n30 STRUCT<n31 STRUCT<n32 STRUCT<n33 STRUCT<n34 STRUCT<n35 STRUCT<n36 STRUCT<n37 STRUCT<n38 STRUCT<n39 STRUCT<n40 STRUCT<n41 STRUCT<n42 STRUCT<n43 STRUCT<n44 STRUCT<n45 STRUCT<n46 STRUCT<n47 STRUCT<n48 STRUCT<n49 STRUCT<n50 STRUCT<n51 STRUCT<n52 STRUCT<n53 STRUCT<n54 STRUCT<n55 STRUCT<n56 STRUCT<n57 STRUCT<n58 STRUCT<n59 STRUCT<n60 STRUCT<n61 STRUCT<n62 STRUCT<n63 INT>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>)
TBLPROPERTIES ("format-version"="3");

-- query 3
-- @skip_result_check=true
INSERT INTO deep_values VALUES
  (1, named_struct('n1', named_struct('n2', named_struct('n3', named_struct('n4', named_struct('n5', named_struct('n6', named_struct('n7', named_struct('n8', named_struct('n9', named_struct('n10', named_struct('n11', named_struct('n12', named_struct('n13', named_struct('n14', named_struct('n15', named_struct('n16', named_struct('n17', named_struct('n18', named_struct('n19', named_struct('n20', named_struct('n21', named_struct('n22', named_struct('n23', named_struct('n24', named_struct('n25', named_struct('n26', named_struct('n27', named_struct('n28', named_struct('n29', named_struct('n30', named_struct('n31', named_struct('n32', named_struct('n33', named_struct('n34', named_struct('n35', named_struct('n36', named_struct('n37', named_struct('n38', named_struct('n39', named_struct('n40', named_struct('n41', named_struct('n42', named_struct('n43', named_struct('n44', named_struct('n45', named_struct('n46', named_struct('n47', named_struct('n48', named_struct('n49', named_struct('n50', named_struct('n51', named_struct('n52', named_struct('n53', named_struct('n54', named_struct('n55', named_struct('n56', named_struct('n57', named_struct('n58', named_struct('n59', named_struct('n60', named_struct('n61', named_struct('n62', named_struct('n63', 7)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))),
  (2, NULL),
  (3, named_struct('n1', named_struct('n2', named_struct('n3', named_struct('n4', named_struct('n5', named_struct('n6', named_struct('n7', named_struct('n8', named_struct('n9', named_struct('n10', named_struct('n11', named_struct('n12', named_struct('n13', named_struct('n14', named_struct('n15', named_struct('n16', named_struct('n17', named_struct('n18', named_struct('n19', named_struct('n20', named_struct('n21', named_struct('n22', named_struct('n23', named_struct('n24', named_struct('n25', named_struct('n26', named_struct('n27', named_struct('n28', named_struct('n29', named_struct('n30', named_struct('n31', named_struct('n32', named_struct('n33', named_struct('n34', named_struct('n35', named_struct('n36', named_struct('n37', named_struct('n38', named_struct('n39', named_struct('n40', named_struct('n41', named_struct('n42', named_struct('n43', named_struct('n44', named_struct('n45', named_struct('n46', named_struct('n47', named_struct('n48', named_struct('n49', named_struct('n50', named_struct('n51', named_struct('n52', named_struct('n53', named_struct('n54', named_struct('n55', named_struct('n56', named_struct('n57', named_struct('n58', named_struct('n59', named_struct('n60', named_struct('n61', named_struct('n62', named_struct('n63', -5))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))));

-- query 4
SELECT id, deep FROM deep_values ORDER BY id;

-- query 5
SELECT id, deep.n1.n2.n3.n4.n5.n6.n7.n8.n9.n10.n11.n12.n13.n14.n15.n16.n17.n18.n19.n20.n21.n22.n23.n24.n25.n26.n27.n28.n29.n30.n31.n32.n33.n34.n35.n36.n37.n38.n39.n40.n41.n42.n43.n44.n45.n46.n47.n48.n49.n50.n51.n52.n53.n54.n55.n56.n57.n58.n59.n60.n61.n62.n63 AS leaf FROM deep_values ORDER BY id;

-- query 6
-- @skip_result_check=true
INSERT INTO deep_values SELECT id + 10, deep FROM deep_values WHERE id = 1;

-- query 7
-- @skip_result_check=true
CREATE TABLE deep_copy AS SELECT id, deep FROM deep_values;

-- query 8
SELECT id, deep FROM deep_copy ORDER BY id;

-- query 9
SELECT count(*) AS total, count(deep) AS non_null FROM deep_copy;

-- query 10
SELECT count(*) AS snapshot_count FROM deep_values$snapshots;

-- query 11
-- @expect_error=DDL type exceeds its node or depth budget
CREATE TABLE too_deep (id BIGINT, deep STRUCT<n1 STRUCT<n2 STRUCT<n3 STRUCT<n4 STRUCT<n5 STRUCT<n6 STRUCT<n7 STRUCT<n8 STRUCT<n9 STRUCT<n10 STRUCT<n11 STRUCT<n12 STRUCT<n13 STRUCT<n14 STRUCT<n15 STRUCT<n16 STRUCT<n17 STRUCT<n18 STRUCT<n19 STRUCT<n20 STRUCT<n21 STRUCT<n22 STRUCT<n23 STRUCT<n24 STRUCT<n25 STRUCT<n26 STRUCT<n27 STRUCT<n28 STRUCT<n29 STRUCT<n30 STRUCT<n31 STRUCT<n32 STRUCT<n33 STRUCT<n34 STRUCT<n35 STRUCT<n36 STRUCT<n37 STRUCT<n38 STRUCT<n39 STRUCT<n40 STRUCT<n41 STRUCT<n42 STRUCT<n43 STRUCT<n44 STRUCT<n45 STRUCT<n46 STRUCT<n47 STRUCT<n48 STRUCT<n49 STRUCT<n50 STRUCT<n51 STRUCT<n52 STRUCT<n53 STRUCT<n54 STRUCT<n55 STRUCT<n56 STRUCT<n57 STRUCT<n58 STRUCT<n59 STRUCT<n60 STRUCT<n61 STRUCT<n62 STRUCT<n63 STRUCT<n64 INT>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>);

-- query 12
SELECT count(*) AS snapshot_count FROM deep_values$snapshots;

-- query 13
-- @cleanup=true
-- @skip_result_check=true
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.deep_copy FORCE;
DROP TABLE IF EXISTS nativedepth64_${uuid0}.ns_${uuid0}.deep_values FORCE;
DROP DATABASE nativedepth64_${uuid0}.ns_${uuid0};
DROP CATALOG nativedepth64_${uuid0};
