[package]
name = "novarocks-mysql-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
mysql_common = "0.32"
novarocks-query-application.workspace = true
opensrv-mysql = { version = "0.7", default-features = false }
tokio = { workspace = true, features = ["net", "rt", "sync", "time"] }
tracing.workspace = true
